version: "3.2"
services:
  php:
    build: './php/'
    container_name: worms1d-php
    ports:
      - '80:8000'
    volumes:
      - ../:/app/
    working_dir: /app/
  mysql:
    image: mongo:4.2.3-bionic
    container_name: worms1d-mongo
    ports:
      - '27017:27017'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    volumes:
      - ../var/mongo:/data/db
